# docker-compose for generating a database erd
version: '3.7'

services:

  schemacrawler:
    image: schemacrawler/schemacrawler
    container_name: schemacrawler
    volumes:
      - type: bind
        source: ../python-package/employee_events/
        target: /home/schcrwlr/testdb
      - type: bind
        source: ../python-package/employee_events/
        target: /home/schcrwlr/share
    entrypoint: ['/opt/schemacrawler/bin/schemacrawler.sh']
    command: --database="share/employee_events.db" --server=sqlite --info-level=standard --command=script --user="" --script-language=python --script=mermaid.py --output-file=share/db-schema.mmd --log-level=CONFIG